import { useWorkspaceContext } from "../context/WorkspaceContext.jsx";

export function useWorkspace() {
  const {
    workspace,
    workspaceAccessToken,
    workspaceIdInput,
    setWorkspaceIdInput,
    workspacePasswordInput,
    setWorkspacePasswordInput,
    requiresWorkspacePassword,
    workspaceOpenError,
    recentWorkspaces,
    openWorkspace,
    openRecentWorkspace,
    removeRecentWorkspace,
    lockWorkspace,
    closeWorkspace,
    deleteWorkspace,
    renameWorkspace,
    renameWorkspaceId,
    updateWorkspaceTitle,
    updateWorkspaceIdentity,
    updatePreferences,
    updateWorkspaceSecurity,
    setWorkspaceSaveHandler,
    runWorkspaceSaveHandler,
    setWorkspace,
  } = useWorkspaceContext();

  // Keep old prop names to minimize churn in components.
  return {
    workspace,
    workspaceAccessToken,
    workspaceId: workspaceIdInput,
    setWorkspaceId: setWorkspaceIdInput,
    workspacePassword: workspacePasswordInput,
    setWorkspacePassword: setWorkspacePasswordInput,
    requiresWorkspacePassword,
    workspaceOpenError,
    recentWorkspaces,
    openWorkspace,
    openRecentWorkspace,
    removeRecentWorkspace,
    lockWorkspace,
    closeWorkspace,
    deleteWorkspace,
    renameWorkspace,
    renameWorkspaceId,
    updateWorkspaceTitle,
    updateWorkspaceIdentity,
    updatePreferences,
    updateWorkspaceSecurity,
    setWorkspaceSaveHandler,
    runWorkspaceSaveHandler,
    setWorkspace,
  };
}
